# Generated by Django 4.1.3 on 2022-12-02 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bid_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 2, 12, 37, 55, 123137)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
