# Generated by Django 4.1.3 on 2022-12-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_category_alter_auction_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
