# Generated by Django 4.1.3 on 2022-12-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='init_bid',
            new_name='price',
        ),
    ]
