# Generated by Django 4.1.3 on 2022-12-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_init_bid_auction_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='image',
            new_name='image_url',
        ),
    ]
