# Generated by Django 4.1.3 on 2022-12-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='init_bid',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
