# Generated by Django 4.1.3 on 2022-12-12 02:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_auction_alter_auction_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 11, 23, 35, 41, 426501)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
