# Generated by Django 4.1.3 on 2022-12-15 20:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auction_active_alter_auction_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='auction',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 15, 17, 21, 29, 21446)),
        ),
    ]
