# Generated by Django 4.1.4 on 2022-12-17 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_comment_auction_alter_auction_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 16, 23, 44, 35, 83895)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=550),
        ),
    ]
