# Generated by Django 4.1.4 on 2022-12-23 13:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_auction_date_time_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 23, 10, 16, 48, 166730)),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('auction', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
            ],
        ),
    ]
