# Generated by Django 4.1.4 on 2022-12-24 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_remove_auction_category_alter_auction_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 24, 18, 22, 11, 864703)),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
